#Originally from https://raw.githubusercontent.com/intel/multus-cni/master/.github/workflows/go-build-test-amd64.yml 
name: Go-build-and-test-amd64
on:
    push:
    pull_request:
    schedule:
      - cron: "0 10 * * *" # everyday at 10 am
jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    env:
      GO111MODULE: on
      TARGET: amd64
    steps:
      - name: Set up Go 1.13
        uses: actions/setup-go@v1
        with:
          go-version: 1.13
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Build
        run: GOARCH="${TARGET}" ./scripts/build.sh

      - name: Go test
        run: ./scripts/test.sh
