name: e2e
on: [pull_request]
jobs:
  e2e-test:
    name: E2E test
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go version
        uses: actions/setup-go@v1
        with:
          go-version: 1.13

      - name: Checkout code into the Go module directory
        uses: actions/checkout@v2

      - name: Get tools
        run: ./scripts/e2e_get_tools.sh

      - name: Setup KinD cluster and setup test env
        run: ./scripts/e2e_setup_cluster.sh

      - name: Execute E2E tests
        run: go test -v -tags virtual ./test/e2e/...
