name: e2e
on: [pull_request, push]
jobs:
  e2e-test-cloud:
    name: E2E test cloud (GitHub VM)
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go version
        uses: actions/setup-go@v1
        with:
          go-version: 1.13

      - name: Checkout code into the Go module directory
        uses: actions/checkout@v2

      - name: Get tools
        run: ./scripts/e2e_get_tools.sh

      - name: Setup KinD cluster and setup test env
        run: ./scripts/e2e_setup_cluster.sh

      - name: Execute E2E tests
        run: go test -timeout 60m ./test/e2e/...

  e2e-test-self-hosted:
    name: E2E test self-hosted
    environment: nri-maintainers
    runs-on: [self-hosted, Linux, hugepages]
    steps:
      - name: Set up Go version
        uses: actions/setup-go@v1
        with:
          go-version: 1.13

      - name: Checkout code into the Go module directory
        uses: actions/checkout@v2

      - name: Get tools
        run: ./scripts/e2e_get_tools.sh

      - name: Setup KinD cluster and setup test env
        run: ./scripts/e2e_setup_cluster.sh

      - name: Execute E2E tests
        run: go test -timeout 60m ./test/e2e/...

      - name: Tear down KinD cluster
        if: always()
        run: ./scripts/e2e_teardown_cluster.sh
