name: e2e_hardware
on:
  pull_request:
    types: [opened, synchronize, reopened, labeled]
jobs:
  e2e-test:
    if: contains(github.event.pull_request.labels.*.name, 'hardware')
    name: E2E test on hardware
    runs-on: self-hosted
    steps:
      - name: Set up Go version
        uses: actions/setup-go@v1
        with:
          go-version: 1.13

      - name: Checkout code into the Go module directory
        uses: actions/checkout@v2

      - name: Get tools
        run: ./scripts/e2e_get_tools.sh

      - name: Setup KinD cluster and setup test env
        run: ./scripts/e2e_setup_cluster.sh

      - name: Execute E2E tests
        run: go test -v -tags hardware ./test/e2e/...

      - name: Tear down KinD cluster
        run: ./scripts/e2e_teardown_cluster.sh
